CREATE TABLE superscription (
 id INTEGER PRIMARY KEY,
 num VARCHAR (30),
 complement VARCHAR (200),
 reference VARCHAR (200),
 city VARCHAR (200),
 state VARCHAR (200),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);