CREATE TABLE request_delicts
(id INTEGER AUTO_INCREMENT PRIMARY KEY,
 request_id INTEGER NOT NULL REFERENCES requests (id),
 delict_id INTEGER NOT NULL REFERENCES delicts (id),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
