CREATE TABLE route
(id INTEGER PRIMARY KEY,
 name VARCHAR(200),
 type VARCHAR(200),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE (name, type));
