CREATE TABLE request_entities
(id INTEGER AUTO_INCREMENT PRIMARY KEY,
 role VARCHAR (20) NOT NULL,
 request_id INTEGER NOT NULL REFERENCES requests (id),
 entity_id INTEGER NOT NULL REFERENCES entities (id),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
