CREATE TABLE request
(id INTEGER PRIMARY KEY,
 complaint VARCHAR (200),
 summary TEXT,
 event_timestamp TIMESTAMP,
 status VARCHAR (20),
 measures TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
