CREATE TABLE request_entity
(id INTEGER PRIMARY KEY,
 request_id INTEGER NOT NULL REFERENCES request (id),
 entity_id INTEGER NOT NULL REFERENCES entity (id),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE (request_id, entity_id));
